spring.application.name=springai_proj_1

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=codellama
#spring.ai.ollama.chat.temperature=0.7

logging.file.name=logs/application.log

logging.level.root=INFO

logging.level.com.springai=DEBUG